# Base Image 
FROM openjdk:17



# Copy the built jar file into the container
COPY ./target/simplilearn-01-spring-jdbc-0.0.1-SNAPSHOT.jar .

# Command to run the application
CMD ["java", "-jar", "simplilearn-01-spring-jdbc-0.0.1-SNAPSHOT.jar"]